version: '3'

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bday-back
    env_file: .env
    ports:
      - "3001:3001"
    volumes:
      - .:/usr/src/app
