openapi: 3.0.0
info:
  title: "API"
  version: "1.0.0"
  description:
    $ref: "errors.yaml#/Description"
tags:
  - name: Bdays
  - name: Templates
paths:
  "/bdays":
    $ref: "bdays.yaml#/More"
  "/bdays/{id}":
    $ref: "bdays.yaml#/One"
  "/templates":
    $ref: "templates.yaml#/CreateTemplate"
  "/templates/{templateId}/{bdayId}":
    $ref: "templates.yaml#/PrepareTemplate"
