openapi: 3.0.0
info:
  title: 'API'
  version: '1.0.0'
  description:
    $ref: 'errors.yaml#/Description'
tags:
  - name: Auth
    description: |
      Список ролей:

      `1` - Администратор

      `2` - Пользователь (не может создавать других пользователей)
  - name: Bdays
  - name: Templates
    description: |
      Для формирования __blocks и attachments__ используйте https://api.slack.com/tools/block-kit-builder
  - name: Slack
paths:
  '/auth/login':
    $ref: 'auth.yaml#/Login'
  '/auth/change_password':
    $ref: 'auth.yaml#/ChangePassword'
  '/auth/create_user':
    $ref: 'auth.yaml#/CreateNewUser'
  '/auth/info':
    $ref: 'auth.yaml#/Info'
  '/auth/list_users':
    $ref: 'auth.yaml#/ListUsers'
  '/bdays':
    $ref: 'bdays.yaml#/More'
  '/bdays/{id}':
    $ref: 'bdays.yaml#/One'
  '/templates':
    $ref: 'templates.yaml#/CreateOrGetAllTemplate'
  '/templates/{templateId}':
    $ref: 'templates.yaml#/GetOrUpdateOrDeleteTemplate'
  '/templates/{templateId}/{bdayId}':
    $ref: 'templates.yaml#/PrepareTemplate'
  '/slack/channel_list':
    $ref: 'slack.yaml#/ChannelList'
  '/slack/test_message':
    $ref: 'slack.yaml#/TestMessage'
